Repository Solvro/web-juwenalia, pull requests merged in 2025-04, with the labels that each got.

#114 feat: copy layout.tsx from PR #113
  src/app/layout.tsx
Labels: size/S

#115 fix: readme typo
  README.md
Labels: documentation, size/XS

#116 fix: countdown date
  src/components/countdown.tsx
Labels: size/XS

#113 feat: solvro analytics
  src/app/layout.tsx
Labels: enhancement, size/S

#118 fix: footer columns, cta text
  src/components/footer.tsx
  src/components/tickets-coming-soon.tsx
Labels: size/M

#120 fix/navbar-button-colors
  package-lock.json
  public/buttons/close-button.svg
Labels: size/M

#123 fix: top margin of no-artist-info component
  src/components/artists/artist-list.tsx
Labels: size/XS

#122 chore: swap out map pin for a custom one
  src/components/map/interactive-map.tsx
  src/components/map/map-pin.tsx
Labels: size/M

#124 fix: artist image size and spacing
  src/components/artists/artist-list.tsx
  src/components/artists/artist.tsx
Labels: size/XS
